version: "2.27"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: planter-web
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
